var { buildSchema } = require('graphql');

module.exports = buildSchema(`
    type Query {
        batches: [Batches],
        transfers: [Transfer]
    }
    type Batches {
        _Key: Float,
        TotalOutflow: Float,
        TotalInflow: Float,
        CurrentStock: Float,
        OpeningStock: Int,
        QualityState: Int,
        ConfirmationState: Int,
        _BatchTypeKey: Float,
        _MaterialKey: Float,
        _UnitKey: Float,
        TheDate: String,
        _EnterpriseKey:	Float,
        ApproachMaterialNumber:	String,
        SupplierBatchNumber: String,
        OrderNumber: String,
        BatchName: String,
        Comment: String,
        _IsDeleted:	Int,
        _1stJob: Float,
        _Name: String,
        Classifications: String,
        _XuClassifications:	Int,
        _XuTotalOutflow: Int,
        _XuTotalInflow:	Int,
        _XuOpeningStock: Int,
        _XuQualityState: Int,
        _XuConfirmationState: Int,
        _Xu_BatchTypeKey: Float,
        _Xu_MaterialKey: Float,
        _Xu_UnitKey: Float,
        _XuStockEndTime: String,
        _XuStockStartTime: String,
        _XuProcessEndTime: String,
        _XuProcessStartTime: String,
        _XuTheDate:	String,
        _XuApproachMaterialNumber:	String,
        _XuSupplierBatchNumber:	String,
        _XuOrderNumber:	String ,                       
        _XuBatchName: String,
        _XuComment:	String,
        _XuEndTime:	String,
        _XuStartTime: String,
        MonthSerial: Float,
        _Xu_PlantKey:	Float,
        _PlantKey:	Float,
        WeekSerial:	Int,
        NonConformityFlag:	Int,
        _Xu_RecipeKey:	Float,
        _RecipeKey:	Float,
        EndTime: String,
        StartTime: String,
        StockEndTime: String,
        StockStartTime: String,
        ProcessEndTime:	String,
        ProcessStartTime: String
    }

    type Transfer {
        _Key: Float,
        Classifications: String,
        UserHint: Int,
        DestinationUnitOfMeasurement: String,
        DestinationAmount: Float,
        SourceUnitOfMeasurement: String,
        SourceAmount: Int,
        _DestinationMaterialKey: Float,
        _SourceMaterialKey: Float,
        _DestinationUnitKey: Float,
        _SourceUnitKey: Float,
        TransferBatchUniversalName: String,
        _TransferBatchKey: Float,
        DestinationBatchUniversalName: String,
        _DestinationBatchKey: Float,
        SourceBatchUniversalName: String,
        _SourceBatchKey: Float,
        StartDate: String,
        ConfirmationState: Int,
        _TransferTypeKey: Float,
        _EnterpriseKey: Float,
        Comment: String,
        _LastJob: Float,
        _1stJob: Float,
        _Name: String,
        DestinationValueTimestamp: String,
        SourceValueTimestamp: String,
        EndTime: String,
        StartTime: String,
        _IsDeleted: Int,
        _XuClassifications: Int,
        _XuDestinationUnitOfMeasurement: Int,
        _XuDestinationAmount: Int,
        _XuSourceUnitOfMeasurement: Int,
        _XuSourceAmount: Int,
        _Xu_DestinationMaterialKey: Float,
        _Xu_SourceMaterialKey: Float,
        _Xu_DestinationUnitKey: Float,
        _Xu_SourceUnitKey: Float,
        _XuTransferBatchUniversalName: String,
        _Xu_TransferBatchKey: Float,
        _XuDestinationBatchUniversalName: String,
        _Xu_DestinationBatchKey: Float,
        _XuSourceBatchUniversalName: String,
        _Xu_SourceBatchKey: Float,
        _XuDestinationValueTimestamp: Float,
        _XuSourceValueTimestamp: Float,
        _XuEndTime: String,
        _XuStartTime: String,
        _XuConfirmationState: Int,
        _Xu_TransferTypeKey: Float,
        _XuComment: String
    }
`);